//# DEMO RENDER (shared)
//+ Pure data/string functions that turn one reference/html/*.html file into the HTML the demo
//+ shows — no DOM, no fetch, no browser globals, so this file runs unchanged in Node
//+ (scripts/build-site-static.js, at build time) and, if ever loaded as a plain <script>, in the
//+ browser too. It is the only "how a reference renders" implementation: build-site-static.js uses
//+ it to pre-bake site/build/demo.content.html and site/page/demo.html (parked there, not yet
//+ promoted to a top-level page), and nothing renders a reference at runtime any more. Keep it in
//+ sync with
//+ scripts/generate-component-docs.js whenever the doc-comment format or the demo markup
//+ conventions (demo="component"/"wrapper", demo-h2/demo-h3, codeNone, previewNone) change.

const { extractAttributes } = require("./pgs-attributes.js");

const TAG_ORDER = ["title", "description", "pgs", "pgs-generated", "pgs-options", "pgs-data", "pgs-state", "api", "related", "return"];
const LIST_TAGS = new Set(["pgs", "pgs-generated", "pgs-options", "pgs-data", "pgs-state", "api", "related"]);
const LIST_TAG_LABELS = {
    pgs: "PGS",
    "pgs-options": "PGS Options (component brackets)",
    "pgs-data": "PGS Data",
    "pgs-generated": "PGS generated by JavaScript",
    "pgs-state": "PGS States",
    api: "API",
    related: "Related elements",
};

const WELCOME_ENTRY = { path: "welcome", title: "Welcome" };

const CATEGORY_LABELS = {
    base: "Base",
    components: "Components",
    layout: "Layout",
    patterns: "Patterns",
    helper: "Helper",
    guides: "Guides",
};

//= the nav, in the order it is shown: a reference file that is not listed here never reaches the
//= demo, whatever else it is wired into
const referenceFiles = [
    "base/body.html",
    "base/general.html",
    "base/border.html",
    "base/hover.html",
    "base/typography.html",
    "base/color.html",
    "base/darkmode.html",
    "base/svg.html",
    "components/notification.html",
    "components/card.html",
    "components/slides.html",
    "components/button.html",
    "components/icon.html",
    "components/formAddon.html",
    "components/form.html",
    "components/search.html",
    "components/summary.html",
    "components/menu.html",
    "components/modal.html",
    "components/pageNav.html",
    "components/stepTabs.html",
    "components/tabs.html",
    "components/accordion.html",
    "components/alerts.html",
    "components/badges.html",
    "components/breadcrumb.html",
    "components/dropdown.html",
    "components/logo.html",
    "components/steps.html",
    "components/table.html",
    "components/toast.html",
    "patterns/cookieConsent.html",
    "layout/header.html",
    "layout/responsive.html",
    "layout/breakpoints.html",
    "layout/spacing.html",
    "layout/size.html",
    "layout/utilities.html",
    "layout/section.html",
    "layout/pageShell.html",
    "layout/footer.html",
    "helper/pgs.html",
    "helper/init.html",
    "helper/formValidate.html",
    "helper/scrollHorizontal.html",
];

const ENTRY_ICONS = {
    "welcome": "fa-house",
    "base/general.html": "fa-sliders",
    "base/border.html": "fa-border-none",
    "base/hover.html": "fa-arrow-pointer",
    "base/typography.html": "fa-heading",
    "base/color.html": "fa-palette",
    "base/darkmode.html": "fa-moon",
    "base/svg.html": "fa-bezier-curve",
    "components/notification.html": "fa-bell",
    "components/card.html": "fa-id-card",
    "components/slides.html": "fa-images",
    "components/button.html": "fa-hand-pointer",
    "components/icon.html": "fa-icons",
    "components/formAddon.html": "fa-puzzle-piece",
    "components/form.html": "fa-pen-to-square",
    "components/search.html": "fa-magnifying-glass",
    "components/summary.html": "fa-list",
    "components/menu.html": "fa-bars",
    "components/modal.html": "fa-window-restore",
    "components/pageNav.html": "fa-map-signs",
    "components/stepTabs.html": "fa-shoe-prints",
    "components/tabs.html": "fa-window-maximize",
    "components/accordion.html": "fa-layer-group",
    "components/alerts.html": "fa-triangle-exclamation",
    "components/badges.html": "fa-tag",
    "components/breadcrumb.html": "fa-route",
    "components/dropdown.html": "fa-caret-down",
    "components/logo.html": "fa-star",
    "components/steps.html": "fa-shoe-prints",
    "components/table.html": "fa-table",
    "components/toast.html": "fa-bread-slice",
    "patterns/cookieConsent.html": "fa-cookie-bite",
    "base/body.html": "fa-file-code",
    "layout/responsive.html": "fa-mobile-screen",
    "layout/breakpoints.html": "fa-ellipsis-vertical",
    "layout/spacing.html": "fa-ruler",
    "layout/size.html": "fa-ruler-combined",
    "layout/utilities.html": "fa-wrench",
    "layout/section.html": "fa-table-cells",
    "layout/pageShell.html": "fa-table-columns",
    "layout/header.html": "fa-arrow-up",
    "layout/footer.html": "fa-arrow-down",
    "helper/pgs.html": "fa-code",
    "helper/init.html": "fa-rotate",
    "helper/formValidate.html": "fa-pen-to-square",
    "helper/scrollHorizontal.html": "fa-arrows-left-right",
};
const DEFAULT_ENTRY_ICON = "fa-square";

//= PATH HELPERS (pure, path-only — no need to open the file to know these)
function getReferenceTitle(path) {
    return path.replace(".html", "").replace("/", " / ");
}

function getSlug(path) {
    return path.replace(/\.html$/, "").replace(/\//g, "-");
}

function getCategory(path) {
    const prefix = path.split("/")[0];
    return CATEGORY_LABELS[prefix] || prefix;
}

function getEntryLabel(path) {
    if (path === WELCOME_ENTRY.path) return WELCOME_ENTRY.title;
    return path.split("/").pop().replace(/\.html$/, "");
}

function escapeHtml(value) {
    return String(value)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");
}

//= reverses escapeHtml, for text read out of an HTML attribute (demo-h2/demo-h3/demo-description):
//= those are written with entities so a literal quote or a "pgs=" example fits inside the
//= attribute's own quotes, but this file only ever regex-matches the raw attribute text, never
//= parses it as HTML. Decoding once here keeps escapeHtml's later, single re-encode correct,
//= instead of encoding an already-encoded string into a visibly broken "&amp;quot;"
function unescapeHtml(value) {
    return String(value)
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&quot;/g, "\"")
        .replace(/&#39;/g, "'")
        .replace(/&amp;/g, "&");
}

function escapeRegExp(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

//= dedents a block by the smallest leading whitespace found among its non-empty lines
function dedent(text) {
    const lines = text.replace(/^\n/, "").replace(/\s+$/, "").split("\n");
    const indents = lines.filter(line => line.trim().length > 0).map(line => line.match(/^\s*/)[0].length);
    const minIndent = indents.length ? Math.min(...indents) : 0;
    return lines.map(line => line.slice(minIndent)).join("\n");
}

//= PARSING (pure string/regex, no validation: npm run docs:generate is what enforces the format is
//= followed correctly)
function parseDocumentation(html) {
    const match = html.match(/<!--[\t\r\n ]*(\/\*\*[\s\S]*?\*\/)[\t\r\n ]*-->[\t\r\n ]*/);
    if (!match) return { data: null, markup: html.trim() };

    const lines = match[1].replace(/\r\n?/g, "\n").split("\n");
    const data = { title: "", description: "", pgs: [], "pgs-generated": [], "pgs-options": [], "pgs-data": [], "pgs-state": [], api: [], related: [], return: "" };
    let activeTag = null;

    for (let index = 1; index < lines.length - 1; index += 1) {
        const bodyMatch = lines[index].match(/^\s*\*(?: ?(.*))?$/);
        const line = (bodyMatch ? bodyMatch[1] || "" : "").trim();
        if (!line) continue;

        const tagMatch = line.match(/^@([a-z-]+)(?:\s+(.*))?$/);
        if (tagMatch) {
            const tag = tagMatch[1];
            if (!TAG_ORDER.includes(tag)) {
                activeTag = null;
                continue;
            }
            activeTag = tag;
            if (!LIST_TAGS.has(tag)) data[tag] = (tagMatch[2] || "").trim();
            continue;
        }

        if (!activeTag || !LIST_TAGS.has(activeTag)) continue;
        const itemMatch = line.match(/^-\s+([^:]+):\s+(.+)$/);
        if (!itemMatch) continue;
        data[activeTag].push({ key: itemMatch[1].trim(), description: itemMatch[2].trim() });
    }

    return { data, markup: html.slice(match.index + match[0].length).trim() };
}

//= pulls a <script type="..."> reference block out of the markup so it can render as its own titled section
function extractScriptBlock(markup, typeValue) {
    const safeType = escapeRegExp(typeValue);
    const pattern = new RegExp(`<script\\b[^>]*\\btype\\s*=\\s*["']${safeType}["'][^>]*>([\\s\\S]*?)<\\/script>`, "i");
    const match = markup.match(pattern);
    if (!match) return { content: null, markup };

    const cleanedMarkup = (markup.slice(0, match.index) + markup.slice(match.index + match[0].length))
        .replace(/\n{3,}/g, "\n\n")
        .trim();

    return { content: dedent(match[1]), markup: cleanedMarkup };
}

//= a whole page skeleton (<!DOCTYPE>, <html>, <head>) is shown as source only, verbatim
function isDocumentMarkup(markup) {
    return /<!DOCTYPE\s|<html[\s>]/i.test(markup);
}

//= mirrors extractAttributes in scripts/generate-component-docs.js: scans the whole markup for
//= pgs/pgs-options/pgs-state attribute usage, used to group @related entries by how they're used
function extractAttributeUsage(markup) {
    const attributes = extractAttributes(markup);
    return {
        pgs: new Set(attributes.pgs),
        "pgs-options": new Set(attributes.options),
        "pgs-data": new Set(attributes.data.map(value => value.split("[")[0])),
        "pgs-state": new Set(attributes.states)
    };
}

//+ finds the index right after the closing tag matching an opening tag of tagName starting at fromIndex
function findMatchingCloseTag(markup, tagName, fromIndex) {
    const tagPattern = new RegExp(`<(\\/?)${tagName}\\b[^>]*>`, "gi");
    tagPattern.lastIndex = fromIndex;
    let depth = 1;
    let match;

    while ((match = tagPattern.exec(markup))) {
        if (match[1]) {
            depth--;
            if (depth === 0) return match.index + match[0].length;
        } else if (!match[0].endsWith("/>")) {
            depth++;
        }
        tagPattern.lastIndex = match.index + match[0].length;
    }

    return -1;
}

function stripDemoAttributesFromMarkup(html) {
    return html.replace(/\s+demo(?:-h2|-h3|-title|-description)?\s*=\s*("[^"]*"|'[^']*')/g, "");
}

//+ an element that only groups the example for the demo is not part of the example: demo="wrapper"
//+ keeps it in the live preview but prints what is inside it instead of itself — only meaningful for
//+ the copyable "Example HTML" text, never for the live preview markup. It can repeat at several
//+ levels side by side within one example (see Border's rows of spans), not just a single nested
//+ chain, so this scans the whole string for a match rather than assuming the next one is always at
//+ the very start.
function unwrapScaffold(markup) {
    let current = markup.trim();
    const openTagPattern = /<([a-zA-Z][a-zA-Z0-9-]*)\b[^>]*>/g;

    while (true) {
        openTagPattern.lastIndex = 0;
        let match;
        let target = null;

        while ((match = openTagPattern.exec(current))) {
            if (/\bdemo\s*=\s*["'][^"']*\bwrapper\b[^"']*["']/.test(match[0])) {
                target = match;
                break;
            }
        }

        if (!target) return current;

        const openEnd = target.index + target[0].length;
        const end = findMatchingCloseTag(current, target[1], openEnd);
        if (end === -1) return current;

        const closing = current.lastIndexOf("<", end - 1);
        const inner = dedent(current.slice(openEnd, closing));

        current = current.slice(0, target.index) + inner + current.slice(end);
    }
}

//+ removes every demo="disabled" element (whole subtree) — used only for the copyable code text,
//+ the live preview always keeps the untouched original markup
function stripDisabledElements(markup) {
    const openTagPattern = /<([a-zA-Z][a-zA-Z0-9-]*)\b[^>]*\bdemo\s*=\s*["']disabled["'][^>]*>/g;
    let result = "";
    let lastIndex = 0;
    let match;

    while ((match = openTagPattern.exec(markup))) {
        const tagName = match[1];
        const openTagEnd = match.index + match[0].length;
        const end = findMatchingCloseTag(markup, tagName, openTagEnd);
        const removeEnd = end === -1 ? openTagEnd : end;

        result += markup.slice(lastIndex, match.index);
        lastIndex = removeEnd;
        openTagPattern.lastIndex = removeEnd;
    }

    result += markup.slice(lastIndex);
    return result.replace(/\n{3,}/g, "\n\n").trim();
}

//+ every custom property a component exposes carries its own name as an exact prefix
//+ (slides.html -> --slides-*), matching extractCssVariables in scripts/generate-component-docs.js
function extractCssVariables(basename, cssText) {
    const pattern = new RegExp(`--${escapeRegExp(basename)}-[A-Za-z0-9-]+`, "g");
    return [...new Set((cssText || "").match(pattern) || [])].sort((a, b) => a.localeCompare(b, "en"));
}

//+ true when a demo="component" element has a nested demo="component" descendant, meaning it's
//+ transparent grouping markup rather than the rendered example itself. The boundary check (rather
//+ than an exact-value match) is what lets "component" combine with codeNone/previewNone in the same
//+ demo attribute, e.g. demo="component previewNone".
function hasNestedComponent(markup, start, end) {
    return /\bdemo\s*=\s*["'][^"']*\bcomponent\b[^"']*["']/.test(markup.slice(start, end));
}

//+ walks the example markup in document order (same rule as extractDemoBlocks in
//+ scripts/generate-component-docs.js): a <demo demo-h2> marker
//+ becomes a heading block, a <demo demo-h3> marker is held as "pending" until the next titleable
//+ leaf consumes it, and a demo="component" with a nested demo="component" is transparent (the walk
//+ keeps scanning through its content instead of treating it as one block, see formAddon.html's
//+ outer <form demo="component"> around several inner ones). demo="wrapper" never appears in this
//+ top-level match at all — it's a purely nested instruction, unwrapped afterwards by unwrapScaffold,
//+ never its own block boundary. `unwrap` controls whether demo="wrapper" elements are unwrapped in
//+ the returned markup — true for the copyable code text, false for the live-preview markup, which
//+ must keep them (removing a real, styled element there would break layout).
function extractDemoBlocks(markup, { unwrap = true } = {}) {
    const pattern = /<(demo)\b[^>]*>|<([a-zA-Z][a-zA-Z0-9-]*)\b[^>]*\bdemo\s*=\s*["'][^"']*\bcomponent\b[^"']*["'][^>]*>/g;
    const blocks = [];
    let pendingH3 = null;
    let match;

    while ((match = pattern.exec(markup))) {
        if (match[1] === "demo") {
            const openTagEnd = match.index + match[0].length;
            const end = findMatchingCloseTag(markup, "demo", openTagEnd);
            const h2Match = match[0].match(/\bdemo-h2\s*=\s*(["'])((?:(?!\1).)*)\1/);
            const h3Match = match[0].match(/\bdemo-h3\s*=\s*(["'])((?:(?!\1).)*)\1/);
            const descriptionMatch = match[0].match(/\bdemo-description\s*=\s*(["'])((?:(?!\1).)*)\1/);
            const description = descriptionMatch ? unescapeHtml(descriptionMatch[2]) : "";

            if (h2Match) blocks.push({ type: "heading", title: unescapeHtml(h2Match[2]), description });
            else if (h3Match) pendingH3 = { title: unescapeHtml(h3Match[2]), description };

            pattern.lastIndex = end === -1 ? openTagEnd : end;
            continue;
        }

        const tagName = match[2];
        const openTagEnd = match.index + match[0].length;
        const end = findMatchingCloseTag(markup, tagName, openTagEnd);
        if (end === -1) {
            pattern.lastIndex = openTagEnd;
            continue;
        }

        if (hasNestedComponent(markup, openTagEnd, end)) {
            pattern.lastIndex = openTagEnd;
            continue;
        }

        let dedented;
        if (unwrap) {
            //== a demo="component" only declares where one example starts: it is the grouping
            //== element, never part of the example itself, so its own tag never reaches the copied
            //== code — exactly like demo="wrapper". The live-preview markup (unwrap: false) always
            //== keeps the real element, since removing it there could change the layout
            const closing = markup.lastIndexOf("<", end - 1);
            dedented = dedent(markup.slice(openTagEnd, closing));
        } else {
            const lineStart = markup.lastIndexOf("\n", match.index) + 1;
            const baseIndent = markup.slice(lineStart, match.index).match(/^[ \t]*$/) ? markup.slice(lineStart, match.index) : "";
            const outer = markup.slice(match.index, end);
            dedented = baseIndent ? outer.replace(new RegExp(`^${escapeRegExp(baseIndent)}`, "gm"), "") : outer;
        }
        const processed = unwrap ? unwrapScaffold(dedented) : dedented;

        blocks.push({
            type: "item",
            title: pendingH3 ? pendingH3.title : "",
            description: pendingH3 ? pendingH3.description : "",
            hideCode: /\bdemo\s*=\s*["'][^"']*\bcodeNone\b[^"']*["']/.test(match[0]),
            previewNone: /\bdemo\s*=\s*["'][^"']*\bpreviewNone\b[^"']*["']/.test(match[0]),
            markup: stripDemoAttributesFromMarkup(processed).trim(),
        });
        pendingH3 = null;

        pattern.lastIndex = end;
    }

    return blocks;
}

//= HTML STRING RENDERING (the part with no generate-component-docs.js equivalent: that script
//= renders Markdown, this renders the demo's own panel HTML)
//+ isPanel turns the list into the accordion's own panel: the token and the initial hidden go on
//+ the <ul> itself, since there is nothing else between it and the accordion root
function renderDocListHtml(items, isPanel = false) {
    const rows = items.map(item => `<li><code>${escapeHtml(item.key)}</code>: ${escapeHtml(item.description)}</li>`).join("");
    return `<ul pgs="flex['column' 'gapTexts']${isPanel ? " accordion-content" : ""}"${isPanel ? " hidden" : ""}>${rows}</ul>`;
}

//== the two lists a reader opens a reference for; the rest stay closed so the doc block does not
//== push the examples below the fold
const DOC_GROUPS_OPEN = new Set([LIST_TAG_LABELS.pgs, LIST_TAG_LABELS["pgs-options"]]);

//+ every top-level group of the doc block is an accordion: the lists are long and a reader is
//+ usually after one of them. The heading is the control — pgs.accordion gives it role="button"
//+ and tabindex, so a heading stays operable — and both it and the panel have to be direct
//+ children of the root, which is what the module looks for. The panel is always written hidden so
//+ it does not flash open before the JavaScript runs; accAutoOpen is what reopens the two
//+ groups above at init. There is no accordionContainer around these on purpose — without a group
//+ each panel answers for itself, so reading one does not collapse the rest of the block
function renderDocAccordionHtml(label, panelHtml, className = "") {
    const classAttribute = className ? ` class="${className}"` : "";
    const accordion = DOC_GROUPS_OPEN.has(label) ? "accordion['accAutoOpen']" : "accordion";
    return `<div${classAttribute} pgs="${accordion}">` +
        `<h4 pgs="accordion-button">${escapeHtml(label)}</h4>` +
        panelHtml +
        `</div>`;
}

//== only the h4 groups become accordions: the h5 buckets live inside the Related panel, and an
//== accordion nested in another one would close its own parent, since opening one closes every
//== other accordion in the document
function renderDocGroupHtml(label, items, level) {
    if (!items.length) return "";
    if (level === "h4") return renderDocAccordionHtml(label, renderDocListHtml(items, true));
    return `<div pgs="flex['column' 'gapTexts']"><${level} class="demoContent-doc-subheading">${escapeHtml(label)}</${level}>${renderDocListHtml(items)}</div>`;
}

function renderRelatedGroupHtml(items, markup) {
    if (!items.length) return "";
    const usage = extractAttributeUsage(markup);
    const isPgs = key => usage.pgs.has(key);
    const isOption = key => usage["pgs-options"].has(key);
    const isData = key => usage["pgs-data"].has(key);
    const isState = key => usage["pgs-state"].has(key);

    const buckets = [
        ["PGS", items.filter(item => isPgs(item.key))],
        ["PGS Options (component brackets)", items.filter(item => !isPgs(item.key) && isOption(item.key))],
        ["PGS Data", items.filter(item => isData(item.key))],
        ["PGS States", items.filter(item => !isPgs(item.key) && !isOption(item.key) && isState(item.key))],
    ];
    const grouped = new Set(buckets.flatMap(([, groupItems]) => groupItems));
    buckets.push(["Other", items.filter(item => !grouped.has(item))]);

    const groupsHtml = buckets.map(([label, groupItems]) => renderDocGroupHtml(label, groupItems, "h5")).join("");
    const panel = `<div pgs="flex['column' 'gapTexts'] accordion-content" hidden>${groupsHtml}</div>`;
    return renderDocAccordionHtml("Related elements", panel, "demoContent-doc-related");
}

function renderCssVariablesGroupHtml(basename, cssText) {
    const variables = extractCssVariables(basename, cssText);
    if (!variables.length) return "";
    const items = variables.map(name => `<li><code>${escapeHtml(name)}</code></li>`).join("");
    const panel = `<ul pgs="flex['column' 'gapTexts'] accordion-content" hidden>${items}</ul>`;
    return renderDocAccordionHtml("CSS Variables", panel, "demoContent-doc-cssVariables");
}

function renderDocumentationHtml(data, markup, basename, cssText) {
    if (!data) return "";
    const parts = [
        renderDocGroupHtml(LIST_TAG_LABELS.pgs, data.pgs || [], "h4"),
        renderDocGroupHtml(LIST_TAG_LABELS["pgs-generated"], data["pgs-generated"] || [], "h4"),
        renderDocGroupHtml(LIST_TAG_LABELS["pgs-options"], data["pgs-options"] || [], "h4"),
        renderDocGroupHtml(LIST_TAG_LABELS["pgs-data"], data["pgs-data"] || [], "h4"),
        renderDocGroupHtml(LIST_TAG_LABELS["pgs-state"], data["pgs-state"] || [], "h4"),
        renderDocGroupHtml(LIST_TAG_LABELS.api, data.api || [], "h4"),
        renderRelatedGroupHtml(data.related || [], markup),
        renderCssVariablesGroupHtml(basename, cssText),
    ].filter(Boolean).join("");
    if (!parts) return "";
    return `<div class="demoContent-doc" pgs="box flex['column' 'gapElements'] accordionContainer">${parts}</div>`;
}

function renderHeadingBlockHtml(title, description, level) {
    if (!title && !description) return "";
    const heading = title ? `<${level} class="demoContent-heading demoContent-heading-${level}">${escapeHtml(title)}</${level}>` : "";
    const desc = description ? `<p>${escapeHtml(description)}</p>` : "";
    return `<div class="demoContent-heading" pgs="flex['column' 'gapTexts']">${heading}${desc}</div>`;
}

function renderExampleSourceHtml(markup, title = "Example HTML", kind = "html") {
    const langClass = kind === "html" ? "markup" : kind;
    return `<div class="exampleSource" data-kind="${escapeHtml(kind)}">` +
        `<strong class="exampleSource-title">${escapeHtml(title)}</strong>` +
        `<button type="button" class="exampleSource-copy" aria-label="Copia il codice HTML"><i class="fa-solid fa-copy" aria-hidden="true"></i></button>` +
        `<pre><code class="language-${langClass}">${escapeHtml(markup)}</code></pre>` +
        `</div>`;
}

function renderReferenceHtml(markup) {
    return `<div pgs="container flex['column' 'gapElements']">${markup}</div>`;
}

function renderDemoItemHtml({ previewMarkup, codeMarkup, title, description, showPreview, hasCode }) {
    let html = `<div class="demo-item" pgs="flex['column' 'gapElements']">`;
    html += renderHeadingBlockHtml(title, description, "h3");
    html += showPreview
        ? `<div pgs="container flex['column' 'gapElements']">${previewMarkup}</div>`
        : `<div pgs="hidden">${previewMarkup}</div>`;
    if (hasCode) html += renderExampleSourceHtml(codeMarkup);
    html += `</div>`;
    return html;
}

//= Splits example markup tagged with demo="component" (titled by a
//= preceding <demo demo-h2/demo-h3> marker, see extractDemoBlocks) into one live-preview + code
//= pair per item, falling back to a single whole-markup pair for reference files that don't use
//= those tags yet
function renderExamplePairsHtml(exampleMarkup) {
    if (!exampleMarkup.trim()) return "";

    const codeSourceMarkup = stripDisabledElements(exampleMarkup);
    const codeBlocks = extractDemoBlocks(codeSourceMarkup, { unwrap: true });

    if (!codeBlocks.length) {
        const code = codeSourceMarkup.trim();
        return renderReferenceHtml(exampleMarkup) + (code ? renderExampleSourceHtml(code) : "");
    }

    //== a second walk over the un-stripped, non-unwrapped markup for the live-preview text; the two
    //== walks line up index-for-index in every case seen in this repo (no demo="disabled" element is
    //== itself a demo="component" root), so the same loop index addresses both
    //== arrays directly — paired defensively (checked, never assumed) rather than by a separate
    //== counter that has to remember to advance in lockstep for every block type, headings included
    const previewBlocks = extractDemoBlocks(exampleMarkup, { unwrap: false });

    let html = "";
    codeBlocks.forEach((block, index) => {
        if (block.type === "heading") {
            html += renderHeadingBlockHtml(block.title, block.description, "h2");
            return;
        }

        const previewBlock = previewBlocks[index];

        html += renderDemoItemHtml({
            previewMarkup: previewBlock && previewBlock.type === "item" ? previewBlock.markup : block.markup,
            codeMarkup: block.markup,
            title: block.title,
            description: block.description,
            showPreview: !block.previewNone,
            hasCode: !block.hideCode,
        });
    });
    return html;
}

//= NAV (path-derived only — never needs to look at a file's content)
function renderNavMenuHtml(items, category) {
    const rows = items.map(({ path }) => {
        const icon = ENTRY_ICONS[path] || DEFAULT_ENTRY_ICON;
        return `<li><a href="#${escapeHtml(getSlug(path))}" pgs="pageNav-list-item button['btnText' 'btnPaddingEqual']">` +
            `<i class="fa-solid ${icon}" aria-hidden="true"></i><span>${escapeHtml(getEntryLabel(path))}</span></a></li>`;
    }).join("");
    return `<nav pgs="pageNav-list menu['menuVertical']" aria-label="Menu ${escapeHtml(category || "")}"><ul pgs="border['brdLeft']">${rows}</ul></nav>`;
}

function renderNavHtml(entries, withHeadingIds = true) {
    const groups = new Map();
    const ungrouped = [];

    entries.forEach(entry => {
        if (!entry.path.includes("/")) {
            ungrouped.push(entry);
            return;
        }
        const prefix = entry.path.split("/")[0];
        if (!groups.has(prefix)) groups.set(prefix, []);
        groups.get(prefix).push(entry);
    });

    const byLabel = (a, b) => getEntryLabel(a.path).localeCompare(getEntryLabel(b.path));

    let html = "";
    if (ungrouped.length) html += renderNavMenuHtml([...ungrouped].sort(byLabel));

    const sortedGroups = [...groups.entries()].sort(([prefixA], [prefixB]) =>
        (CATEGORY_LABELS[prefixA] || prefixA).localeCompare(CATEGORY_LABELS[prefixB] || prefixB)
    );

    sortedGroups.forEach(([prefix, items]) => {
        const category = CATEGORY_LABELS[prefix] || prefix;
        const idAttr = withHeadingIds ? ` id="${escapeHtml(prefix)}"` : "";
        html += `<p${idAttr}><strong>${escapeHtml(category)}</strong></p>`;
        html += renderNavMenuHtml([...items].sort(byLabel), category);
    });

    return html;
}

//= TOP LEVEL: turns one reference/html/*.html file's raw text into its full panel HTML — the
//= header, the doc block, the script-block sections and the rendered examples
function renderReferencePanelHtml(path, rawFileText, cssText) {
    const isSection = path !== "layout/section.html" && path !== "layout/pageShell.html";
    let title = getReferenceTitle(path);
    let bodyHtml;

    try {
        const { data, markup } = parseDocumentation(rawFileText);
        if (data?.title) title = data.title;

        bodyHtml = renderHeadingBlockHtml(title, data?.description, "h1");
        bodyHtml += renderDocumentationHtml(data, markup, getEntryLabel(path), cssText);

        const { content: jsonSchema, markup: afterJson } = extractScriptBlock(markup, "application/json");
        const { content: jsUsage, markup: exampleMarkup } = extractScriptBlock(afterJson, "text/x-example-js");

        if (jsonSchema) bodyHtml += renderExampleSourceHtml(`pgs-data='${jsonSchema}'`, "PGS Data fields", "json");
        if (jsUsage) bodyHtml += renderExampleSourceHtml(jsUsage, "JavaScript Usage", "js");

        bodyHtml += isDocumentMarkup(exampleMarkup)
            ? renderExampleSourceHtml(exampleMarkup.trim())
            : renderExamplePairsHtml(exampleMarkup);
    } catch (error) {
        bodyHtml = renderHeadingBlockHtml(title, "", "h1") + `<p>Riferimento non caricato: ${escapeHtml(error.message)}</p>`;
    }

    const sectionTag = isSection ? "section" : "div";
    const sectionExtraAttrs = isSection ? ` pgs="flex['column' 'gapElements']"` : ` style="display:contents"`;
    const section = `<${sectionTag} class="demoContent" data-reference="${escapeHtml(path)}"${sectionExtraAttrs}>${bodyHtml}</${sectionTag}>`;
    //== no flex utility here: the section above already lays out its own content, and
    //== pageNav-panels-content's own display is fully owned by _pageNav.scss (see there for why)
    const panel = `<div id="${escapeHtml(getSlug(path))}" pgs="pageNav-panels-content">${section}</div>`;

    return { title, panelHtml: panel };
}

const DemoRender = {
    TAG_ORDER, LIST_TAGS, LIST_TAG_LABELS, CATEGORY_LABELS, ENTRY_ICONS, DEFAULT_ENTRY_ICON,
    referenceFiles, WELCOME_ENTRY,
    getReferenceTitle, getSlug, getCategory, getEntryLabel, escapeHtml,
    parseDocumentation, extractScriptBlock, isDocumentMarkup, extractAttributeUsage,
    extractCssVariables, extractDemoBlocks,
    renderHeadingBlockHtml, renderExampleSourceHtml, renderReferenceHtml, renderDemoItemHtml,
    renderExamplePairsHtml, renderDocumentationHtml,
    renderNavMenuHtml, renderNavHtml,
    renderReferencePanelHtml,
};

if (typeof module !== "undefined" && module.exports) module.exports = DemoRender;
if (typeof globalThis !== "undefined") globalThis.DemoRender = DemoRender;
